name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  function-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]


    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install -y python3-pytest python3-pip
    - run: mkdir db
    - run: pytest -v include/test.py
